x-mariadb-image: &mariadb-version mariadb:11.5.2
x-mariadb-env: &cenv                       # https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases
  MARIADB_RANDOM_ROOT_PASSWORD: 'true'
  MARIADB_DATABASE: ${DB_NAME}
  MARIADB_USER: ${DB_USER}
  MARIADB_PASSWORD: ${DB_PASSWORD}
x-grr-env: &grr
  GRR_ADMIN_PASSWORD: ${GRR_ADMIN_PASSWORD}
services:
  db: # mysql
    image: *mariadb-version      # https://hub.docker.com/_/mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
    environment:
      <<: *cenv                # https://yaml.org/type/merge.html
    restart: unless-stopped
  init:
    image: *mariadb-version
    environment:
      <<: [*cenv, *grr]        # https://yaml.org/type/merge.html
    command: /init/init_db.sh
    volumes:
      - ./app/src/installation/tables.my.sql:/etc/init_data/tables.my.sql:ro
      - ./backups/sql:/etc/init_data/backups:rw
      - ./init/scripts:/init
    depends_on:
      db:
        condition: service_healthy
  app: # apache + mod_php
    build:
      context: ./app # uses app/Dockerfile
      args:
        PHP_VERSION: 8.3
    volumes:
    - type: volume
      source: uploads
      target: /var/www/html/personnalisation/images
    ports:
      - "${EXTERNAL_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
      init:
          condition: service_completed_successfully
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
volumes:
  db_data:
  uploads:
