x-mariadb-image: &mariadb-version mariadb:11.5.2
x-mariadb-env: &cenv                       # https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases
  MARIADB_RANDOM_ROOT_PASSWORD: 'true'
  MARIADB_DATABASE: ${DB_NAME}
  MARIADB_USER: ${DB_USER}
  MARIADB_PASSWORD: ${DB_PASSWORD}
x-grr-env: &grr
  GRR_ADMIN_PASSWORD: ${GRR_ADMIN_PASSWORD}
services:
  db: # mysql
    image: *mariadb-version      # https://hub.docker.com/_/mariadb
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/mysql
    environment:
      <<: *cenv                # https://yaml.org/type/merge.html
    restart: unless-stopped
  init:
    image: *mariadb-version
    environment:
      <<: [*cenv, *grr]        # https://yaml.org/type/merge.html
    command: /init/init_db.sh
    volumes:
      - ./app/src/installation/tables.my.sql:/etc/init_data/tables.my.sql:ro
      - ./init/scripts:/init
    depends_on:
      db:
        condition: service_started
  app: # apache + mod_php
    build:
      context: ./app # uses app/Dockerfile
    volumes:
    - type: volume
      source: uploads
      target: /var/www/html/personnalisation/images
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      init:
          condition: service_completed_successfully
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
volumes:
  db_data:
  uploads:
